spring:
  application:
    name: authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

server:
  port: 8087
