server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # Permite atualizar as tabelas automaticamente de acordo com o código
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
